### PR TITLE
new type encoding

### LINKED ISSUE #36: Bad saving of interactively-defined function in tuple
The function disappears from the tuple:

```julia
julia> using JLD2, FileIO

julia> f(x) = x+1
f (generic function with 1 method)

julia> save("test.jld2", "tuple", (f, :hello))

### New session

julia> using JLD2, FileIO

julia> load("test.jld2", "tuple")
(:hello,)
```

### LINKED ISSUE #175: Warning on attempt to save anonymous function
Consider the following.

    $ julia
                   _
       _       _ _(_)_     |  Documentation: https://docs.julialang.org
      (_)     | (_) (_)    |
       _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
     _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
    |__/                   |
    
    julia> using JLD2
    
    julia> A = Any[x->x]
    1-element Array{var"#7#8",1}:
     var"#7#8"()
    
    julia> @save "A.jld2" A
    
    julia> exit()
    $ julia
                   _
       _       _ _(_)_     |  Documentation: https://docs.julialang.org
      (_)     | (_) (_)    |
       _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
     _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
    |__/                   |
    
    julia> using JLD2
    
    julia> @load "A.jld2" A
    ┌ Warning: type Main.#9#10 does not exist in workspace; reconstructing
    └ @ JLD2 ~/.julia/dev/JLD2/src/data.jl:1066
    1-element Array{Symbol,1}:
     :A
        
I understand that it will never be practical to save anonymous functions in a HDF file.  However, it would be helpful if `@save` raised a warning when you tried to do that.

Among other things, it would save users from repeatedly raising this issue.

I ran across this when I tried to save a `DifferentialEquations.ODESolution`.  That is the kind of thing you want to save, and it would be nice to get a warning when the `ODESolution` for `dx/dt = f(t,x)` includes `f` as an anonymous function.

Related issues: #13 #86

### LINKED ISSUE #401: Saving a struct with an anonymous function type in a type parameter is highly non future-proof
I've got a struct which has an anonymous function as a field, with the type in the struct type parameters. I don't need to serialize the function, I can reconstruct it at load-time, but since its anonymous it might have a new "name" upon reconstructing if the order of anonymous functions defined in the running session / containing module ever changes. This seems to cause JLD2 to error since the type parameters may not be exactly the same when reconstructing. Something like this:

```julia

using JLD2

# define struct and custom serialization
struct FunWrap{F}
    f :: F
    function FunWrap()
        f = () -> 1
        new{typeof(f)}(f)
    end
end
JLD2.writeas(::Type{<:FunWrap}) = Tuple{}
JLD2.wconvert(::Type{Tuple{}}, f::FunWrap) = ()
JLD2.rconvert(::Type{<:FunWrap}, ::Tuple{}) = FunWrap()


f = FunWrap()
@save "test.jld2" f
# redefine to create a new name for the anonymous function. this
# simulates making some (even completely unrelated) change to the
# contianing module
struct FunWrap{F} 
    f :: F
    function FunWrap()
        f = () -> 1
        new{typeof(f)}(f)
    end
end
@load "test.jld2" f
# ERROR: TypeError: in typeassert, expected FunWrap{var"#7#8"}, got a value of type FunWrap{var"#11#12"}
```

Is there any way to get this to work? Doesn't seem like the custom serialization helps here, and neither would `typemap`. 

I should mention the real use-case is saving an Interpolations.jl object, which uses an anonymous function. Its not hard to make a custom serialization which just saves the data and tries to recreate the Interpolation object at load-time, but loading can then fail due to the issue above. Thanks for any help.

### PR DESCRIPTION
**Pull request by JonasIsensee**
closes #36 
closes #175 
closes #401

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
https://buildkite.com/julialang/diffeqdocs-dot-jl/builds/223#0191d1f5-c702-45da-963a-a962086318cc/1645-3461

This seems to have a bug? Is it tested on types that have more parameters than fields?

**Comment by JonasIsensee** [comment]
It seems that I cannot access the logs you linked.

**Comment by ChrisRackauckas** [comment]
```julia



Debug: Evaluating @example block:
  | │ using OrdinaryDiffEq, DataFrames
  | │ f_2dlinear = (du, u, p, t) -> du .= 1.01u;
  | │ tspan = (0.0, 1.0)
  | │ prob = ODEProblem(f_2dlinear, rand(2, 2), tspan);
  | │ sol = solve(prob, Euler(); dt = 1 // 2^(4));
  | │ df = DataFrame(sol)
  | └ @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/expander_pipeline.jl:737
  | ┌ Debug: Evaluating @example block:
  | │ f = ODEFunction(f_2dlinear, syms = [:a, :b, :c, :d])
  | │ prob = ODEProblem(f, rand(2, 2), (0.0, 1.0));
  | │ sol = solve(prob, Euler(); dt = 1 // 2^(4));
  | │ df = DataFrame(sol)
  | └ @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/expander_pipeline.jl:737
  | ┌ Debug: Evaluating @example block:
  | │ using CSV
  | │ CSV.write("out.csv", df)
  | └ @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/expander_pipeline.jl:737
  | ┌ Debug: Evaluating @example block:
  | │ sol = solve(prob, Euler(); dt = 1 // 2^(4))
  | │ using JLD2
  | │ @save "out.jld2" sol
  | └ @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/expander_pipeline.jl:737
  | ┌ Debug: Evaluating @example block:
  | │ # New session
  | │ using JLD2
  | │ using OrdinaryDiffEq
  | │ JLD2.@load "out.jld2" sol
  | └ @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/expander_pipeline.jl:737
  | ┌ Error: failed to run `@example` block in src/features/io.md:54-59
  | │ ```@example IO
  | │ # New session
  | │ using JLD2
  | │ using OrdinaryDiffEq
  | │ JLD2.@load "out.jld2" sol
  | │ ```
  | │   exception =
  | │    NamedTuple names and field types must have matching lengths
  | │    Stacktrace:
  | │      [1] reconstruct_compound(f::JLD2.JLDFile{JLD2.MmapIO}, T::String, dt::JLD2.CompoundDatatype, field_datatypes::OrderedCollections.OrderedDict{String, JLD2.RelOffset})
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/data/reconstructing_datatypes.jl:617
  | │      [2] constructrr(f::JLD2.JLDFile{JLD2.MmapIO}, unk::Type{JLD2.UnknownType{ODEFunction, Tuple{true, SciMLBase.FullSpecialize, JLD2.UnknownType{Symbol("Main.__atexample__named__IO.#1#2"), Tuple{}}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, SymbolicIndexingInterface.SymbolCache{Dict{Symbol, Int64}, Nothing, Nothing, Nothing, Dict{Any, Any}}, Nothing, Nothing}}}, dt::JLD2.CompoundDatatype, attrs::Vector{JLD2.ReadAttribute})
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/data/reconstructing_datatypes.jl:575
  | │      [3] jltype(f::JLD2.JLDFile{JLD2.MmapIO}, sdt::JLD2.CommittedDatatype)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/data/reconstructing_datatypes.jl:115
  | │      [4] types_from_refs(f::JLD2.JLDFile{JLD2.MmapIO}, ptr::Ptr{Nothing})
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/data/reconstructing_datatypes.jl:331
  | │      [5] jlconvert(rr::JLD2.ReadRepresentation{DataType, JLD2.OnDiskRepresentation{(0, 16), Tuple{String, Vector{Any}}, Tuple{JLD2.Vlen{String}, JLD2.Vlen{JLD2.RelOffset}}, 32}()}, f::JLD2.JLDFile{JLD2.MmapIO}, ptr::Ptr{Nothing}, header_offset::JLD2.RelOffset)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/data/reconstructing_datatypes.jl:347
  | │      [6] read_scalar(f::JLD2.JLDFile{JLD2.MmapIO}, rr::Any, header_offset::JLD2.RelOffset)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/dataio.jl:37
  | │      [7] read_data(f::JLD2.JLDFile{JLD2.MmapIO}, rr::Any, read_dataspace::Tuple{JLD2.ReadDataspace, JLD2.RelOffset, JLD2.DataLayout, JLD2.FilterPipeline}, attributes::Vector{JLD2.ReadAttribute})
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/datasets.jl:98
  | │      [8] read_data(f::JLD2.JLDFile{JLD2.MmapIO}, dataspace::JLD2.ReadDataspace, dt::JLD2.H5Datatype, layout::JLD2.DataLayout, filters::JLD2.FilterPipeline, header_offset::JLD2.RelOffset, attributes::Vector{JLD2.ReadAttribute})
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/datasets.jl:86
  | │      [9] load_dataset(f::JLD2.JLDFile{JLD2.MmapIO}, offset::JLD2.RelOffset)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/datasets.jl:50
  | │     [10] types_from_refs(f::JLD2.JLDFile{JLD2.MmapIO}, ptr::Ptr{Nothing})
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/data/reconstructing_datatypes.jl:331
  | │     [11] jlconvert(rr::JLD2.ReadRepresentation{DataType, JLD2.OnDiskRepresentation{(0, 16), Tuple{String, Vector{Any}}, Tuple{JLD2.Vlen{String}, JLD2.Vlen{JLD2.RelOffset}}, 32}()}, f::JLD2.JLDFile{JLD2.MmapIO}, ptr::Ptr{Nothing}, header_offset::JLD2.RelOffset)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/data/reconstructing_datatypes.jl:347
  | │     [12] read_scalar(f::JLD2.JLDFile{JLD2.MmapIO}, rr::Any, header_offset::JLD2.RelOffset)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/dataio.jl:37
  | │     [13] read_data(f::JLD2.JLDFile{JLD2.MmapIO}, rr::Any, read_dataspace::Tuple{JLD2.ReadDataspace, JLD2.RelOffset, JLD2.DataLayout, JLD2.FilterPipeline}, attributes::Nothing)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/datasets.jl:98
  | │     [14] read_data(f::JLD2.JLDFile{JLD2.MmapIO}, dataspace::JLD2.ReadDataspace, dt::JLD2.H5Datatype, layout::JLD2.DataLayout, filters::JLD2.FilterPipeline, header_offset::JLD2.RelOffset, attributes::Nothing)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/datasets.jl:86
  | │     [15] read_data (repeats 2 times)
  | │        @ ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/datasets.jl:69 [inlined]
  | │     [16] read_attr_data
  | │        @ ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/attributes.jl:91 [inlined]
  | │     [17] jltype(f::JLD2.JLDFile{JLD2.MmapIO}, sdt::JLD2.SharedDatatype)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/data/reconstructing_datatypes.jl:98
  | │     [18] read_data(f::JLD2.JLDFile{JLD2.MmapIO}, dataspace::JLD2.ReadDataspace, dt::JLD2.H5Datatype, layout::JLD2.DataLayout, filters::JLD2.FilterPipeline, header_offset::JLD2.RelOffset, attributes::Vector{JLD2.ReadAttribute})
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/datasets.jl:69
  | │     [19] load_dataset(f::JLD2.JLDFile{JLD2.MmapIO}, offset::JLD2.RelOffset)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/datasets.jl:50
  | │     [20] getindex(g::JLD2.Group{JLD2.JLDFile{JLD2.MmapIO}}, name::String)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/groups.jl:99
  | │     [21] read
  | │        @ ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/JLD2.jl:368 [inlined]
  | │     [22] (::Main.__atexample__named__IO.var"#3#4")(f::JLD2.JLDFile{JLD2.MmapIO})
  | │        @ Main.__atexample__named__IO ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/loadsave.jl:153
  | │     [23] jldopen(f::Function, args::String; kws::@Kwargs{})
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/loadsave.jl:4
  | │     [24] jldopen(f::Function, args::String)
  | │        @ JLD2 ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/JLD2/vAW4N/src/loadsave.jl:1
  | │     [25] top-level scope
  | │        @ io.md:152
  | │     [26] eval
  | │        @ ./boot.jl:385 [inlined]
  | │     [27] #60
  | │        @ ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/expander_pipeline.jl:754 [inlined]
  | │     [28] cd(f::Documenter.var"#60#62"{Module, Expr}, dir::String)
  | │        @ Base.Filesystem ./file.jl:112
  | │     [29] (::Documenter.var"#59#61"{Documenter.Page, Module, Expr})()
  | │        @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/expander_pipeline.jl:753
  | │     [30] (::IOCapture.var"#5#9"{DataType, Documenter.var"#59#61"{Documenter.Page, Module, Expr}, IOContext{Base.PipeEndpoint}, IOContext{Base.PipeEndpoint}, Base.TTY, Base.TTY})()
  | │        @ IOCapture ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/IOCapture/Y5rEA/src/IOCapture.jl:170
  | │     [31] with_logstate(f::Function, logstate::Any)
  | │        @ Base.CoreLogging ./logging.jl:515
  | │     [32] with_logger
  | │        @ ./logging.jl:627 [inlined]
  | │     [33] capture(f::Documenter.var"#59#61"{Documenter.Page, Module, Expr}; rethrow::Type, color::Bool, passthrough::Bool, capture_buffer::IOBuffer, io_context::Vector{Any})
  | │        @ IOCapture ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/IOCapture/Y5rEA/src/IOCapture.jl:167
  | │     [34] runner(::Type{Documenter.Expanders.ExampleBlocks}, node::MarkdownAST.Node{Nothing}, page::Documenter.Page, doc::Documenter.Document)
  | │        @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/expander_pipeline.jl:752
  | └ @ Documenter ~/.cache/julia-buildkite-plugin/depots/0185fce3-4489-413a-a934-123dd653ef61/packages/Documenter/C1XEF/src/utilities/utilities.jl:44
 

<br class="Apple-interchange-newline">
```

**Comment by JonasIsensee** [comment]
Thank you, I found the issue.
Two methods were not covered by tests and, hence, were missed while updating.
I'll tag a patch with new tests and the fix today.

**Comment by ChrisRackauckas** [comment]
Thanks!

**Comment by JonasIsensee** [comment]
Bugfix along with new tests is merged and I pinged the registrator for `v0.5.1`
The example from your stacktrace works locally but I used a different file for tests to avoid adding `OrdinaryDiffEq` as a test-dep.

I hope, your pipelines will run with this.
If not, please be patient with me,
building representative tests to cover the space of all possible structs and type signatures is never a finished task.

**Comment by ChrisRackauckas** [comment]
Confirmed that fixes our use case.

**Pull request merged**
