### PR TITLE
round trip tests with functional values

### PR DESCRIPTION
**Pull request by kolia**
Didn't have enough insight into whether #260 is a good idea or not, so instead I wrote some tests.

These tests round trip various objects containing a function value `f` (issue #258.)

On master, 8 fail, 2 pass.

On the `reconstructfunctions` branch of PR #260, 2 fail: `[f]` and `[f, f]`, though for some reason round tripping `[f, 42]` works just fine.

For comparison, all of these tests pass for v0.2.4.

### CODE REVIEW

**Comment by JonasIsensee** [comment]
Hey !
This is awesome! Thank you, this will definitely help in resolving the problem :+1:

**Comment by JonasIsensee** [comment]
Btw. have you by any chance tested this against `v0.2.4` ?

**Comment by kolia** [comment]
Yes, all these tests pass against `v0.2.4`.

**Comment by JonasIsensee** [comment]
Great!
Thanks again! :)

**Pull request merged**
