### PR TITLE
Revert "Align writeas for Dict with wconvert"

### PR DESCRIPTION
**Pull request by sjkelly**
Reverts JuliaIO/JLD2.jl#492

Re #497 

Should likely have a patch release or alternative fix.

### CODE REVIEW

**Comment by JonasIsensee** [comment]
I'll implement the fix tomorrow.

**Comment by sjkelly** [comment]
Okay I will tag a patch release temporarily so stable releases of Julia are not broken. The original change was for nightly AFAICT

**Comment by sjkelly** [comment]
Oh I just saw #499

**Comment by JonasIsensee** [comment]
The #499 should work for both nightly and with non standard dict types.
I merged it just now

**Pull request merged**
