### PR TITLE
v0.5.0

### PR DESCRIPTION
**Pull request by JonasIsensee**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
What is breaking in this change?

**Comment by JonasIsensee** [comment]
This is breaking at the file format level.
New files cannot be read by older versions of the library.
Existing files can still be read and there are no breaking API changes.

**Comment by ChrisRackauckas** [comment]
Can you add that to the news?

**Comment by JonasIsensee** [comment]
It is in the changelog.
I can copy it into the description of this PR and into the release notes ,I guess

**Pull request merged**
