### PR TITLE
Fix segmentation fault when reading a file that doesn't exist

### LINKED ISSUE #183: Segmentation fault
The following code snippet produces a segmentation fault:
```
using JLD2

jfn, _ = mktemp()
jldopen(string(jfn, ".jld2"), "a+") do ds
    ds["1"] = 1.0
end

#jldopen(string(jfn, ".jld2"), "r") do jds
jldopen(jfn, "r") do jds
    println(jds["1"])
end
```
The fault looks like:
```

signal (11): Segmentation fault
in expression starting at /central/home/kpamnany/tmp/jld2bugmwe.jl:9
macro expansion at ./pointer.jl:65 [inlined]
read! at ./io.jl:681 [inlined]
#jldopen#9 at /central/home/kpamnany/CLIMA/.julia_depot/packages/JLD2/hB4ya/src/JLD2.jl:241
jldopen at /central/home/kpamnany/CLIMA/.julia_depot/packages/JLD2/hB4ya/src/JLD2.jl:203 [inlined]
jldopen at /central/home/kpamnany/CLIMA/.julia_depot/packages/JLD2/hB4ya/src/JLD2.jl:203 [inlined]
#jldopen#10 at /central/home/kpamnany/CLIMA/.julia_depot/packages/JLD2/hB4ya/src/JLD2.jl:293
jldopen at /central/home/kpamnany/CLIMA/.julia_depot/packages/JLD2/hB4ya/src/JLD2.jl:288
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2135 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
#jldopen#31 at /central/home/kpamnany/CLIMA/.julia_depot/packages/JLD2/hB4ya/src/loadsave.jl:2
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2141 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
jldopen at /central/home/kpamnany/CLIMA/.julia_depot/packages/JLD2/hB4ya/src/loadsave.jl:2
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2135 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1631 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:328
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:417
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:368 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:778
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:888
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x2aaad839740f)
unknown function (ip: 0x6)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:897
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:814
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:873
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:878
include at ./boot.jl:328 [inlined]
include_relative at ./loading.jl:1105
include at ./Base.jl:31
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2135 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
exec_options at ./client.jl:287
_start at ./client.jl:460
jfptr__start_2084.clone_1 at /central/software/julia/1.3.0/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2135 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
unknown function (ip: 0x401931)
unknown function (ip: 0x401533)
__libc_start_main at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x4015d4)
Allocations: 8768916 (Pool: 8766924; Big: 1992); GC: 9
Segmentation fault
```

### PR DESCRIPTION
**Pull request by kpamnany**
Fixes #183.

### CODE REVIEW

**Comment by timholy** [comment]
Thanks! Can you add a test that would have triggered the segfault?

**Comment by timholy** [comment]
Still segfaulting. Let us know when you're happy with this.

**Comment by kpamnany** [comment]
Ah. Turns out that `MmapIO` actually does throw a `SystemError` if the file doesn't exist. I wondered how come this simple check was missing.

The problem is that `mktemp()` creates the file so it does exist, but is empty (?). And now, the `read!` [here](https://github.com/JuliaIO/JLD2.jl/blob/master/src/JLD2.jl#L241) is seg-faulting and I don't really understand why.

**Comment by JonasIsensee** [comment]
My commit seems to fix the problem by introducing a new check that tests whether the filesize is zero.

However I do not understand why the test failed. Locally it worked for the new test some old test seems to break due to these changes.

**Comment by kpamnany** [comment]
@timholy: I think this is the right fix.

**Comment by JonasIsensee** [comment]
also fixes #136

**Comment by JonasIsensee** [comment]
Does anyone else have an opinion on this?
I'd say we can merge this.

I'm not a big fan of the error message and feel like we could add proper filepath assertions but that will be a PR in its own right.

**Comment by kpamnany** [comment]
Fixed the conflict.

**Comment by timholy** [comment]
Seems OK to me. Indeed the error message does not rate high on verbosity but perhaps it's not easy to clearly convey the precise nature of the problem at this stage? It seems useful to have this fix as the "last interceptor" and then perhaps we could add other checks at an earlier stage in the pipeline. We could modify the test to still check this particular fix.

**Comment by kpamnany** [comment]
Haha, well, it's an `mmap` system error! We'd need to check `errno` for more I think.

**Comment by JonasIsensee** [comment]
> Seems OK to me. Indeed the error message does not rate high on verbosity but perhaps it's not easy to clearly convey the precise nature of the problem at this stage? It seems useful to have this fix as the "last interceptor" and then perhaps we could add other checks at an earlier stage in the pipeline. We could modify the test to still check this particular fix.

Exactly, that is what I was thinking of.
I don't think it will be necessary to dissect the `errno`. (Would that even work across different OS?)
Currently you will get this error any time mmap fails even if mmap is not really the problem.
It should be relatively easy to check whether the give filepath 
 1) contains a filename (don't try to open a folder e.g. #136
 2) all directories in the path exist

When all those cases are taken care of, one could even wrap the mmap-open into a `try` block and use `IOStream` as a fallback.
(Which would of course be pointless if mmap is not actually the problem)

**Pull request merged**
